### ISSUE TITLE
The description of the klusterlet status InvalidRegistrationFeatureGates contradicts itself

### ISSUE THREAD

**Issue by zhujian7** [open-cluster-management-io/registration-operator#289]
As you can see, the `InvalidRegistrationFeatureGates` is `True`, but the reason is `FeatureGatesAllValid`
```
status:
  conditions:
  - lastTransitionTime: "2022-10-27T08:49:35Z"
    message: Registration feature gates of klusterlet are all valid
    reason: FeatureGatesAllValid
    status: "True"
    type: InvalidRegistrationFeatureGates
```

OCM version: 0.9.0
