### ISSUE TITLE
Allow klusterlet to patch hostAliases when creating klusterlet-registration-agent deployment

### ISSUE THREAD

**Issue by abdennour** [open-cluster-management-io/registration-operator#318]
Hi, 
  IF we want to add `hostAliases` in all deployments under the namespace `open-cluster-management-agent`. So the Managed Cluster can resolve hostname of hub cluster API.
```yaml
# patch
spec:
  template:
    spec:
     hostAliases:
       - ip: a.b.x.y
         hostnames:
           - api.company.lan
```
We patched `klusterlet` deployment, it's fine.. but when we patched `klusterlet-registration-agent` , it get overriden.

There is a permanent way to patch `klusterlet-registration-agent` by hostAliases and in general by any Pod Spec.
